### ISSUE TITLE
pairs有问题

### ISSUE THREAD

**Issue by ghost319** [cloudwu/tablepointer#2]
local tpmgr = require "tablepointer"
local t = {user = 1}
local pt = tpmgr.topointer(t)

for _,k,v in tpmgr.pairs(pt) do
       print(_,k,v)
end
这样没打印,只要table里面有且只有一个非array的就会没打印

**Comment by ghost319** [comment]
把t->lsizenode > 0 改成 t->lsizenode >= 0 好像就可以了
当t->lsizenode == 0的时候也可能有1个node

**Comment by cloudwu** [comment]
修了，顺带还修了另一个 bug 。子 table 遍历出来的指针不对。
